### ISSUE TITLE
Test problem

### ISSUE THREAD

**Issue by zhangkp1997** [id9502/Option-GAIL#2]
I've obtained some models(.torch) via training, but how to test them? Is there a test.py like option_gail_learn.py ?

**Comment by zhangkp1997** [comment]
I've found it ..... helper/render_learned_model.py

**Comment by id9502** [comment]
Sorry for replying late. Assuming you have already pip3 install tensorboard and get your training result at <root_dir>/result/xxx/model, then you can view the learning curve from web browser at http://127.0.0.1:8000 after running this tensorboard command:

`cd <root_dir>`
`tensorboard --logdir ./result --port 8091 --bind_all`

More over, for direct seeing the learned policy, please use <root_dir>/helper/render_learned_model.py by calling:

`cd <root_dir>`
`python3 -m helper.render_learned_model <full path to your exp>/xxx.torch <full path to your exp>/config.log`

After this you will see the gym rendered window for your learned model on exp

**Comment by zhangkp1997** [comment]
> Sorry for replying late. Assuming you have already pip3 install tensorboard and get your training result at <root_dir>/result/xxx/model, then you can view the learning curve from web browser at http://127.0.0.1:8000 after running this tensorboard command:
> 
> `cd <root_dir>` `tensorboard --logdir ./result --port 8091 --bind_all`
> 
> More over, for direct seeing the learned policy, please use <root_dir>/helper/render_learned_model.py by calling:
> 
> `cd <root_dir>` `python3 -m helper.render_learned_model <full path to your exp>/xxx.torch <full path to your exp>/config.log`
> 
> After this you will see the gym rendered window for your learned model on exp

Thank you very much!
