### ISSUE TITLE
Missing function calculate_log_pi_tr

### ISSUE THREAD

**Issue by zbzhu99** [id9502/Option-GAIL#3]
Hello, when I run the code in option_bc_learn.py, it seems the function `calculate_log_pi_tr` is missing, which is used in:
https://github.com/id9502/Option-GAIL/blob/af3a0917f55c6b15aa12fbae3c41b35695346210/option_bc_learn.py#L100
Thank you for your time!

**Comment by id9502** [comment]
Hi, the MAP-based methods are left over from earlier experiments and are deprecated for future use. I have made a new commit and add an explanation.
The MLE-based method are mathematically equivalent to MAP methods, but having higher computation efficiency, you can try it instead.
