### ISSUE TITLE
CloseMicrowave2 task does not converge

### ISSUE THREAD

**Issue by backupaccount0** [id9502/Option-GAIL#4]
Hi, thank you for your work.
I was trying to train a model for task Closemicrowave2, but it does not converge. 
Could you please let me know the version of RLbench you installed? 

And any other advice on the training process? I just followed the command in  run_exps.sh
`python3 ./option_gail_learn.py --env_type rlbench --env_name CloseMicrowave2 --use_option True --use_c_in_discriminator True --n_demo 1000 --device "cuda:0" --use_state_filter True --tag option-gail-1k
`

Thanks a lot!

**Comment by id9502** [comment]
Hi, the rlbench I used for this exp is at https://github.com/id9502/RLBench.git. The problem you found is a flaw in the original paper: the CloseMicrowave2 task has difficulty converging with most IL/HIL methods, where the success rate may reach high values at first, but jitter as training progresses. Comparing on this environment is mainly to show which method can achieve a higher success rate earlier, so the comparison is made by the maximum avg-r-sum, or in other words, the highest avg r-sum value along the training progresses.
